### ISSUE TITLE
IATI Standard website shows old version (2.02) by default from certain links

### ISSUE THREAD

**Issue by markbrough** [IATI/IATI-Standard-SSOT#193]
Currently, the IATI Standard website directs to an older version (v2.02). For example:
http://reference.iatistandard.org/codelists/OrganisationType/

redirects to:
http://reference.iatistandard.org/202/codelists/OrganisationType/ (not `203`)

Similarly, if you click anything in the "IATI Reference" section from the [front page of the documentation website](http://reference.iatistandard.org/), it takes you to `202` and not `203`.

My guess is it's something to do with this:
https://github.com/IATI/IATI-Websites/blob/master/iatistandard/redirects-root.conf

I agree with @andylolz that it would be great if the reference pages were auto-deployed from Github (#164), as I guess it would make it much easier to see what's happening here :)

**Comment by andylolz** [comment]
> My guess is it's something to do with this:
> https://github.com/IATI/IATI-Websites/blob/master/iatistandard/redirects-root.conf

Yeah, that’s exactly right.

I flagged this as a potential problem back in March here: IATI/IATI-Websites#188.

Then it became a problem a month ago, so I raised it here: IATI/IATI-Websites#220.

Then three weeks ago I sent a (one character change) fix for the problem: IATI/IATI-Websites#221.

Sorry to sound so long-suffering. The fix here is trivial, and the problem was totally avoidable. It would be cool to get this fixed.

**Comment by samuele-mattiuzzo** [comment]
Sorted in https://github.com/IATI/IATI-Websites/pull/221

**Comment by andylolz** [comment]
:clap: :rocket: :guitar:

I realised, though (mentioned elsewhere) that this redirect should probably be a 302 / 307, so browsers don’t cache quite so aggressively.

**Comment by samuele-mattiuzzo** [comment]
Hah, bit of status code discussion, I like that.

I think this is a case of "307", but alas we can use 302, so that we stay compatible with HTTP-1.0, which is a non issue except maybe for robots crawling the site or... internet hermits that live on old laptops they connect once a day just to check emails (Any resemblance to actual persons, living or dead, or actual events is purely coincidental)

Sorry, bit of a geeky joke :P 307 is good here 👍

**Comment by samuele-mattiuzzo** [comment]
Been here for a while and with the new home for the ref site being re built, I'm marking the redirect part as obsolete so we can close this and move on
