### ISSUE TITLE
If the withdrawn code is the first in the list, the "withdrawn" style gets applied to the wrong element

### ISSUE THREAD

**Issue by samuele-mattiuzzo** [IATI/IATI-Standard-SSOT#222]
Example:

http://reference.iatistandard.org/202/codelists/BudgetIdentifierVocabulary/

it should be applied to the row element, but instead gets applied to the row's parent, tbody (as per screenshot)

<img width="368" alt="screenshot 2018-11-07 at 14 14 06" src="https://user-images.githubusercontent.com/1381563/48136436-9145a600-e297-11e8-802f-b44dac78e317.png">

**Comment by andylolz** [comment]
Ooph… Nice catch!

I took a look and *I could not for the life of me* figure out how to get this to work the right way in sphinx!

The best I could manage to fix this (in a hacky way) was:

 * Add a hidden stub column (containing the codelist status)
 * Put the withdrawn class on the stub column cell
 * Style the cells in the row using a ~ css selector

I’ll send PRs now, in case it’s useful.

Refs #175.

**Comment by samuele-mattiuzzo** [comment]
Yeah been tinkering around a bit with this myself, Sphinx's `rst-class` has a nasty way of dealing with `first elements` in iterations, apparently! I'll compare your PRs with the uncommitted code I wrote, they seem to be slightly different in how they deal with it.

Nasty Sphinx :(

**Comment by andylolz** [comment]
> Nasty Sphinx :(

Absolutely agree (though I’m sure others think it’s great!)

> they seem to be slightly different in how they deal with it.

If you can find a nicer way, that would be great. Surely it must exist?! #223 seems less than ideal :\ So I’ll hold off on sending the PRs for the other version branches.

If you do decide to go with #223 though, let me know and I’ll send the PRs for the other branches.

**Comment by samuele-mattiuzzo** [comment]
Yeah, will do! My idea is to try to modify the rst file / Sphinx to consolidate the behaviour, as it seems strange that it wouldn't allow the style to be applied to "all elements but the first" in a list. Very uncommon edge case :/

**Comment by andylolz** [comment]
> My idea is to try to modify the rst file / Sphinx to consolidate the behaviour

Yeah, that would be much nicer!

I messed about indenting and moving stuff about in the rst file, then running gen_html.sh (much faster than a full rebuild) and couldn’t find the right permutation!

It seems like it might be a bug with `list-table`, just because I don’t see why this would ever be the desired behaviour.

**Comment by andylolz** [comment]
> My idea is to try to modify the rst file / Sphinx to consolidate the behaviour

Right, yeah – that would be muuuch nicer!

I messed about indenting and moving stuff about in the rst file, then running gen_html.sh (much faster than a full rebuild) but just couldn’t find the right permutation!

> Very uncommon edge case :/

+1. It seems like it might be a bug with `list-table`, just because I don’t see why this would ever be the desired behaviour. Could maybe try switching to use a different sort of table?
