### ISSUE TITLE
How should new category codelists be named and displayed?

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Standard-SSOT#28]
These are:
http://dev.iatistandard.org/codelists/AidType-category/
http://dev.iatistandard.org/codelists/BudgetIdentifierSector/
http://dev.iatistandard.org/codelists/BudgetIdentifierSector-category/
http://dev.iatistandard.org/codelists/DocumentCategory-category/
http://dev.iatistandard.org/codelists/FinanceType-category/

And the previously existing `SectoryCategory`:
http://dev.iatistandard.org/codelists/SectorCategory/

**Comment by caprenter** [comment]
Just to be clear - these lists have been made from other existing lists that had additional category information. A more consistent approach is to break these out into their own lists.

Some of these lists already existed in the 'codelist API' available at data.ainfolabs.org - but were not replicated at iatistandard.org. They were originally made as 'helper' lists rather than 'official' IATI lists.

**Comment by Bjwebb** [comment]
I think we decided to output these codelists on the iatistandard website, but clearly describe them as category codelsits.
