### ISSUE TITLE
page last updated

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Standard-SSOT#42]
eg: 

http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/location/gazetteer-entry/

> Last updated on 2014-04-24

I'm aware that this has been discussed elsewhere, but wanted to suggest that perhaps this could also link to the last commit for that page?

Stylistically (which should be at IATI-Websites perhaps) this could be `smaller` !

**Comment by Bjwebb** [comment]
Since the Single Source of Truth is made up of multiple repositories, not all of which are versioned in sync, linking to the last commit is not straightforward. Therefore, I don't think this is feasible for 1.04, so I'm moving it into the Future milestone.

**Comment by Bjwebb** [comment]
In https://github.com/IATI/IATI-Websites/issues/101 @stevieflow has also suggested moving the last updated text to the footer. Like linking the commit, this is not straightforward.

**Comment by samuele-mattiuzzo** [comment]
Closing this since adding the commit does not add much value to a page (plus, the deployed commit is always the latest commit of `version-xxx` branch, albeit with a delay between commit and actual deployment).
Will consider showing the correct tag once they get implemented. Page last updated (date and time) is still an ongoing issue.

**Comment by andylolz** [comment]
> plus, the deployed commit is always the latest commit of `version-xxx` branch

^^ It would be awesome if this were true, but it definitely isn’t (as previously discussed.) Continuous deployment FTW

**Comment by samuele-mattiuzzo** [comment]
edited.
